version: '3.8'

services:
  sdb:
    image: sdb_image:latest
    build: .
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: main_db
    volumes:
      - ./pg_db:/var/lib/postgresql/data

  vdb:
    image: semitechnologies/weaviate:latest
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      QUERY_DEFAULTS: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    ports:
      - "${WV_PORT}:8080"
    volumes:
      - ./wv_db:/var/lib/weaviate
